### ISSUE TITLE
[Feature Request]: "Upgrade" airstrikes using the "donate to air support" feature.

### ISSUE THREAD

**Issue by PineCone227** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#147]
### Related problem

Currently, any airstrike called in by FIA will be performed by a Caesar BTT light civilian craft dropping ordnance. While we can pretend it's a Super Tucano or similar COIN aircraft, it makes little sense for the call-in to be performed by such an underpowered aircraft(it almost looks as if a joke or gag of some kind), especially considering that calling in an airstrike requires holding an airbase, and airbases are typically captured full of military CAS aircraft. An example of this is taking over Altis International and obtaining several A-149 Gryphon and A-143 Buzzard's, then calling in an airstrike only for a literal Cessna to show up. Currently there's no use for the 'donate to pool' feature, as airstrike points generate on their own, and wasting a (theoretically infinitely) re-usable jet aircraft for a **_single_** Cessna airstrike is the epitome of wastefulness.

### Proposed feature

The solution to the above problem would be allowing airstrikes to be "upgraded" to a better aircraft type by donating a captured aircraft to the airstrike pool. Upon capturing an airbase, the default airstrike aircraft would still be the Caesar BTT, however, if the resistance managed to not bomb every hangar on the base and capture it with some jet craft intact, they could be donated to the airstrike pool and in turn the called-in airstrikes would now be provided by the type of aircraft that was donated. If several aircraft types were added to the pool, the preferred vessel for the airstrike could be selected by a drop-down menu before calling it in. The mechanic could be additionally balanced by adding monetary costs to airstrikes performed by more advanced craft, as to reflect maintenance spending. 

Hinging on this proposed mechanic could be another, giving you the ability to request the help of air superiority aircraft at a high enough war level, provided one of such type has been captured beforehand. The call-in would have a friendly A-A equipped jet circle a designated area providing air cover to the ground teams for a set amount of time before retreating. If this should be put in a separate feature request, please notify me and I'll post a separate issue.

**Comment by Silence-112** [comment]
Adding extra planes to every single rebel template we have simply isn't feasible

**Comment by wersal454** [comment]
Will have to wait until blackmarket vehicles rework is finished, after that maybe there will be a rework of current rebels support system.

**Comment by Silence-112** [comment]
I don't see any feasible way to do this without building it directly into the garage, which we won't be doing.
