### ISSUE TITLE
[Feature Request]: Allow to 'stack all' money into the faction funds/Placing the rest of the funds into the bank if below 250

### ISSUE THREAD

**Issue by FuckingStealingNames** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#258]
### Related problem

You have less than 250 funds, and you wanted to deposit it all since dying would just mean you lose it all from a heavy fund loss setting run.

### Proposed feature

Allow the math to round even if below 250 or just have an ability to place all money into the faction instantly so it doesn't require spamming the button.

**Comment by Silence-112** [comment]
Completed by #261
