### ISSUE TITLE
Server [Bug]: 

### ISSUE THREAD

**Issue by compoundchris** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#267]
### Describe the bug

After restart, if no player is defined as server member no items can be bought, the top resources bar will not load, the faction will not get paid, etc. When a player joins who is defined as a server member or logged in as admin, the top bar appears for players, things are able to be bought, faction gets paid, etc. 

I believe it is the "call A3A_fnc_assignBossIfNone" located within "spawn A3A_fnc_resourcecheck" located in "fn_initserver" We went through what happened after restart in the rpt and this is where it seemed to get stuck until after a member logged in. 

### How to reproduce

Have a dedicated server restart, and then a player who is not logged in as admin or defined as member log in, wait for server to initialize , then that player will not be able to buy anything(demonstration of bug). Then have a player who is logged in as admin or defined as member and the resource check function will work(economy loads). 

### Version

at least since 10.9

### Have you altered the code?

No

### Map

any

### What server?

Private dedicated server with Headless client(s)

### Additional context

[arma3server-console-2024-07-12-00_00_01.log](https://github.com/user-attachments/files/16448091/arma3server-console-2024-07-12-00_00_01.log)

**Comment by s3gfaultx** [comment]
Can confirm the same thing, it's all broken for us too.

**Comment by Silence-112** [comment]
I assume you have it set to auto load last save after a timeout?

**Comment by compoundchris** [comment]
> I assume you have it set to auto load last save after a timeout?

Yes, everything loads except anything to do with economy. All enemy units, we get attacked, we can pull from garage, etc. just can’t buy and faction pay doesn’t happen.

**Comment by s3gfaultx** [comment]
Also to add, a lot of the generated areas (airfields, etc) have the name null. Most of the top bar is missing information (undercover status, war level, etc). Let me know what I can provide to help diagnose.

**Comment by stutpip123** [comment]
full modlist, server and client RPTs

**Comment by compoundchris** [comment]
We are working on getting you a new rpt from a server with only antistasi and its dependencies on it. 
in the rpt I provided, there is evidence of one of a non members trying to buy something before I logged in if that helps!

**Comment by Silence-112** [comment]
What are you unable to buy before a member joins?

**Comment by compoundchris** [comment]
Anything, both blackmarket and the flag buy menu

**Comment by Silence-112** [comment]
Try see if this is fixed in [Public Testing](https://steamcommunity.com/sharedfiles/filedetails/?id=3169463443)
