### ISSUE TITLE
[Feature Request]: Temporary alliance with a Faction

### ISSUE THREAD

**Issue by Araz0** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#300]
### Related problem

Attacking big bases | airports could be challenging for Solo players.
this could be due to lack of resources or skill

This idea might add another depth of operations making the field more dynamic and a lot can happen.

### Proposed feature

Maybe with more dynamic relationships between the factions, we can have a chance to send a message to a faction to attack a location. 
If that request is accepted, then our factions can be friendly for some time and both have the objective to attack a location.
another challenge might arise when we want to decide who gets the base after its destroyed.

### Alternative solutions

instead of an alliance with a faction, we can just ask them to attack a location. but everyone is still enemy.

**Comment by Silence-112** [comment]
Given this would require rewriting huge amounts of the framework, it isn't really feasible

There has been a discussion about very light collaboration between the rebels and occ/inv but nothing is concrete yet

**Comment by Silence-112** [comment]
Going to close this issue. If someone wants to do this, can be re-opened
