### ISSUE TITLE
[Bug]: Incorrect vehicle price value in vehicle market

### ISSUE THREAD

**Issue by PlayerBotPro** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#350]
### Describe the bug

On map with no seaport, capture more than 9 resource will cause incorrect vehicle price in black market and HQ vehicle market

Negative price values on black market: 
![image](https://github.com/user-attachments/assets/1fb01214-4e04-4cd6-8887-01821c888abb)

Vehicle price on HQ goes to 1000$: 
![image](https://github.com/user-attachments/assets/e04d1cbe-3854-46c3-8317-bbeb069253cc)

### How to reproduce

1. Capture 10 resource
2. Open Vehicle Black Market or HQ vehicle market

```sqf
{
    [teamPlayer,_x] remoteExec ["A3A_fnc_markerChange",2];
} forEach resourcesX;
blackMarketIgnoreRequirements=true;
createDialog "A3A_BlackMarketDialog"
```

### Version

11.1.0

### Have you altered the code?

No

### Map

LYTHIUM

### What server?

Private dedicated server

### Time bug occured (Server time/UTC)

13:37

### Mods

```html
CBA_A3
Antistasi Ultimate - Mod
```

**Comment by Silence-112** [comment]
Changed in #350
