### ISSUE TITLE
disableTrader causes server to get stuck on "Starting game..."

### ISSUE THREAD

**Issue by Ricool06** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#353]
https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/blob/2f51290da902844987cf9825cfe003bb46c98140/A3A/addons/scrt/Trader/fn_trader_createTrader.sqf#L14

As of the latest update, our server gets stuck on "Starting game..."
After checking the logs, I can see the following:

```
20:47:53 2024-10-07 19:47:53:021 | Antistasi | Info | File: A3A_fnc_loadStat | Occupants defeated: false | Called By: A3A_fnc_getStatVariable
20:47:53 2024-10-07 19:47:53:021 | Antistasi | Info | File: A3A_fnc_loadStat | Invaders defeated: false | Called By: A3A_fnc_getStatVariable
20:47:53 Error in expression <





params ["_position"];

if (disableTrader) exitWith {};

traderO>
20:47:53   Error position: <if (disableTrader) exitWith {};

traderO>
20:47:53   Error if: Type Number, expected Bool
20:47:53 File x\A3A\addons\scrt\Trader\fn_trader_createTrader.sqf..., line 14
```

I'm guessing disableTrader was never initialised and is causing this error.

**Comment by Silence-112** [comment]
Common issue when the mod doesn't get updated/uploaded correctly. This happens with every update in which we add new parameters

Reuploading the mod should fix it

**Comment by Ricool06** [comment]
> Common issue when the mod doesn't get updated/uploaded correctly. This happens with every update in which we add new parameters
> 
> Reuploading the mod should fix it

Just did a fresh reupload. Same error occurred. I'm going to reinstall the server to find out if that fixes things.

**Comment by Ricool06** [comment]
We had to completely reinstall the server to get the new update to work, but we were able to load our save, so no big deal. Cheers.
