### ISSUE TITLE
[Bug]: Duplicated stringtable entry: "STR_A3AP_setupFactionsTab_ldf"

### ISSUE THREAD

**Issue by regiregi22** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#367]
### Describe the bug

When trying to use the tool Tabler to check and correct the spanish translation, it detected that duplicated string error on the file \A3-Antistasi-Ultimate\A3A\addons\scrt\Stringtable.xml:

### How to reproduce

Find that string on the document to check it is actually duplicated

### Version

11.2.1

### Have you altered the code?

No

### Map

Any map

### What server?

Private dedicated server

**Comment by regiregi22** [comment]
Not that this is anything urgent, but this issue is blocking me from using the tool "Tabler" to complete the whole spanish translation of Antistasi Ultimate. So as soon as this or any order duplicated string gets fixed, I can start working on it :-)

**Comment by Silence-112** [comment]
Done in #370
